PS1='\u@\h \w$(GIT_PS1_SHOWDIRTYSTATE=1 __git_ps1)\$ '

#Environment
#------------------------------------------------------------
if [ -f ~/.system/env ]; then
    . ~/.system/env
fi

#Virtualenv
#------------------------------------------------------------
export WORKON_HOME=$HOME/.virtualenvs

if [ -f /usr/local/bin/virtualenvwrapper.sh ]; then
	source /usr/local/bin/virtualenvwrapper.sh
fi

#RVM
#------------------------------------------------------------
PATH=$PATH:$HOME/.rvm/bin #Add RVM to PATH
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function

#Functions
#------------------------------------------------------------
if [ -f ~/.system/functions ]; then
    . ~/.system/functions
fi

#Aliases
#------------------------------------------------------------
if [ -f ~/.system/aliases ]; then
    . ~/.system/aliases
fi

if [ -f ~/.git-scm/aliases ]; then
    . ~/.git-scm/aliases
fi

#Auto Complete
#------------------------------------------------------------
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

if [ -f ~/.git-scm/git-prompt.sh ]; then
    source ~/.git-scm/git-prompt.sh
fi

if [ -f ~/.git-scm/git-completion.bash ]; then
    source ~/.git-scm/git-completion.bash
fi
